// Do not edit directly; this file is generated automatically.

import UIKit

final class CoreUIDarkTheme: TWDarkAppTheme, TWCoreUITheme, TWThemeProtocol {
    var backgroundAccentColor: UIColor { return .twitchPurple8 }
    var backgroundAccentAltColor: UIColor { return .twitchPurple7 }
    var backgroundAccentAlt2Color: UIColor { return .twitchPurple6 }
    var backgroundAltColor: UIColor { return .twitchHintedGrey3 }
    var backgroundAlt2Color: UIColor { return .twitchHintedGrey4 }
    var backgroundBaseColor: UIColor { return .twitchHintedGrey2 }
    var backgroundBodyColor: UIColor { return .twitchHintedGrey1 }
    var backgroundBrandColor: UIColor { return .twitchPurple11 }
    var backgroundButtonColor: UIColor { return .twitchPurple7 }
    var backgroundButtonActiveColor: UIColor { return .twitchPurple7 }
    var backgroundButtonAlertColor: UIColor { return .twitchRed }
    var backgroundButtonAlertActiveColor: UIColor { return .twitchRed }
    var backgroundButtonAlertFocusColor: UIColor { return .twitchRedDarker }
    var backgroundButtonAlertHoverColor: UIColor { return .twitchRedDarker }
    var backgroundButtonBrandColor: UIColor { return .twitchPurple9 }
    var backgroundButtonBrandActiveColor: UIColor { return backgroundButtonBrandColor }
    var backgroundButtonBrandHoverColor: UIColor { return .twitchPurple8 }
    var backgroundButtonDestructiveActiveColor: UIColor { return backgroundButtonErrorActiveColor }
    var backgroundButtonDestructiveDefaultColor: UIColor { return backgroundButtonErrorColor }
    var backgroundButtonDestructiveHoverColor: UIColor { return backgroundButtonErrorHoverColor }
    var backgroundButtonDisabledColor: UIColor { return .twitchOpacW3 }
    var backgroundButtonErrorColor: UIColor { return .twitchRed10 }
    var backgroundButtonErrorActiveColor: UIColor { return backgroundButtonErrorColor }
    var backgroundButtonErrorHoverColor: UIColor { return .twitchRed12 }
    var backgroundButtonFocusColor: UIColor { return .twitchPurple8 }
    var backgroundButtonHoverColor: UIColor { return .twitchPurple8 }
    var backgroundButtonIconOverlayActiveColor: UIColor { return backgroundInteractableOverlayActiveColor }
    var backgroundButtonIconOverlayDefaultColor: UIColor { return .twitchTransparent }
    var backgroundButtonIconOverlayHoverColor: UIColor { return backgroundInteractableOverlayHoverColor }
    var backgroundButtonInfoColor: UIColor { return .twitchBlue11 }
    var backgroundButtonInfoActiveColor: UIColor { return backgroundButtonInfoColor }
    var backgroundButtonInfoHoverColor: UIColor { return .twitchBlue13 }
    var backgroundButtonOverlayColor: UIColor { return .twitchTransparent }
    var backgroundButtonOverlayBrandColor: UIColor { return .twitchWhite }
    var backgroundButtonOverlayBrandActiveColor: UIColor { return backgroundButtonOverlayBrandColor }
    var backgroundButtonOverlayBrandHoverColor: UIColor { return .twitchOpacW14 }
    var backgroundButtonOverlayDisabledColor: UIColor { return .twitchOpacW2 }
    var backgroundButtonOverlayErrorColor: UIColor { return backgroundButtonErrorColor }
    var backgroundButtonOverlayErrorActiveColor: UIColor { return backgroundButtonOverlayErrorColor }
    var backgroundButtonOverlayErrorHoverColor: UIColor { return backgroundButtonErrorHoverColor }
    var backgroundButtonOverlayFocusColor: UIColor { return .twitchOpacW1 }
    var backgroundButtonOverlayHoverColor: UIColor { return .twitchOpacW1 }
    var backgroundButtonOverlayInfoColor: UIColor { return .twitchBlue11 }
    var backgroundButtonOverlayInfoActiveColor: UIColor { return backgroundButtonOverlayInfoColor }
    var backgroundButtonOverlayInfoHoverColor: UIColor { return .twitchBlue13 }
    var backgroundButtonOverlayPrimaryActiveColor: UIColor { return .twitchOpacW13 }
    var backgroundButtonOverlayPrimaryDefaultColor: UIColor { return .twitchWhite }
    var backgroundButtonOverlayPrimaryHoverColor: UIColor { return .twitchOpacW14 }
    var backgroundButtonOverlaySecondaryActiveColor: UIColor { return backgroundInteractableOverlayActiveColor }
    var backgroundButtonOverlaySecondaryDefaultColor: UIColor { return .twitchOpacW3 }
    var backgroundButtonOverlaySecondaryHoverColor: UIColor { return backgroundInteractableOverlayHoverColor }
    var backgroundButtonOverlaySuccessColor: UIColor { return backgroundButtonSuccessColor }
    var backgroundButtonOverlaySuccessActiveColor: UIColor { return backgroundButtonOverlaySuccessColor }
    var backgroundButtonOverlaySuccessHoverColor: UIColor { return backgroundButtonSuccessHoverColor }
    var backgroundButtonOverlayTextActiveColor: UIColor { return backgroundInteractableOverlayActiveColor }
    var backgroundButtonOverlayTextDefaultColor: UIColor { return .twitchTransparent }
    var backgroundButtonOverlayTextHoverColor: UIColor { return backgroundInteractableOverlayHoverColor }
    var backgroundButtonOverlayWarnColor: UIColor { return .twitchOrange12 }
    var backgroundButtonOverlayWarnActiveColor: UIColor { return backgroundButtonOverlayWarnColor }
    var backgroundButtonOverlayWarnHoverColor: UIColor { return .twitchOrange14 }
    var backgroundButtonPrimaryActiveColor: UIColor { return backgroundButtonBrandActiveColor }
    var backgroundButtonPrimaryDefaultColor: UIColor { return backgroundButtonBrandColor }
    var backgroundButtonPrimaryHoverColor: UIColor { return backgroundButtonBrandHoverColor }
    var backgroundButtonPurchaseColor: UIColor { return .twitchOpacB5 }
    var backgroundButtonSecondaryActiveColor: UIColor { return backgroundInteractableActiveColor }
    var backgroundButtonSecondaryDefaultColor: UIColor { return .twitchOpacW3 }
    var backgroundButtonSecondaryHoverColor: UIColor { return backgroundInteractableHoverColor }
    var backgroundButtonStatusColor: UIColor { return backgroundButtonSuccessColor }
    var backgroundButtonStatusActiveColor: UIColor { return backgroundButtonErrorActiveColor }
    var backgroundButtonStatusFocusColor: UIColor { return backgroundButtonErrorHoverColor }
    var backgroundButtonStatusHoverColor: UIColor { return backgroundButtonErrorHoverColor }
    var backgroundButtonSuccessColor: UIColor { return .twitchGreen12 }
    var backgroundButtonSuccessActiveColor: UIColor { return backgroundButtonSuccessColor }
    var backgroundButtonSuccessFocusColor: UIColor { return .twitchGreenDarker }
    var backgroundButtonSuccessHoverColor: UIColor { return .twitchGreen14 }
    var backgroundButtonTextActiveColor: UIColor { return backgroundInteractableActiveColor }
    var backgroundButtonTextDefaultColor: UIColor { return .twitchTransparent }
    var backgroundButtonTextHoverColor: UIColor { return backgroundInteractableHoverColor }
    var backgroundButtonWarnColor: UIColor { return .twitchOrange12 }
    var backgroundButtonWarnActiveColor: UIColor { return backgroundButtonWarnColor }
    var backgroundButtonWarnHoverColor: UIColor { return .twitchOrange14 }
    var backgroundChatColor: UIColor { return .twitchPurple1 }
    var backgroundChatAltColor: UIColor { return .twitchPurple3 }
    var backgroundChatHeaderColor: UIColor { return .twitchPurple2 }
    var backgroundChatLineMentionedColor: UIColor { return .twitchHintedGrey15 }
    var backgroundChatLineMentioningColor: UIColor { return .twitchHintedGrey5 }
    var backgroundErrorColor: UIColor { return .twitchRed11 }
    var backgroundFloatColor: UIColor { return .twitchHintedGrey3 }
    var backgroundGraphColor: UIColor { return .twitchPurple2 }
    var backgroundGraphFillColor: UIColor { return .twitchPurple8 }
    var backgroundImageSelectorOverlayColor: UIColor { return .twitchTransparent }
    var backgroundInfoColor: UIColor { return .twitchBlue12 }
    var backgroundInputColor: UIColor { return .twitchOpacW4 }
    var backgroundInputCheckboxCheckedColor: UIColor { return borderBrandColor }
    var backgroundInputCheckboxCheckedBackgroundColor: UIColor { return .twitchBlack }
    var backgroundInputCheckboxCheckedBackgroundOverlayColor: UIColor { return .twitchBlack }
    var backgroundInputCheckboxCheckedOverlayColor: UIColor { return .twitchWhite }
    var backgroundInputCheckedColor: UIColor { return .twitchPurple8 }
    var backgroundInputFocusColor: UIColor { return .twitchBlack }
    var backgroundInputOverlayColor: UIColor { return .twitchOpacB4 }
    var backgroundInputOverlayFocusColor: UIColor { return .twitchBlack }
    var backgroundInteractableActiveColor: UIColor { return .twitchOpacW3 }
    var backgroundInteractableAlphaActiveColor: UIColor { return .twitchOpacW5 }
    var backgroundInteractableAlphaHoverColor: UIColor { return .twitchOpacW4 }
    var backgroundInteractableAlphaSelectedColor: UIColor { return .twitchOpacW3 }
    var backgroundInteractableDestructiveActiveColor: UIColor { return .twitchRed }
    var backgroundInteractableDestructiveHoverColor: UIColor { return .twitchRedDarker }
    var backgroundInteractableHoverColor: UIColor { return .twitchOpacW4 }
    var backgroundInteractableOverlayActiveColor: UIColor { return .twitchOpacW3 }
    var backgroundInteractableOverlayHoverColor: UIColor { return .twitchOpacW4 }
    var backgroundInteractableOverlaySelectedColor: UIColor { return .twitchWhite }
    var backgroundInteractableSelectedColor: UIColor { return backgroundButtonBrandColor }
    var backgroundLiveColor: UIColor { return .twitchRed }
    var backgroundModalColor: UIColor { return .twitchPurple3 }
    var backgroundModalOverlayColor: UIColor { return .twitchOpacB13 }
    var backgroundOverlayColor: UIColor { return .twitchOpacB9 }
    var backgroundOverlayBrandColor: UIColor { return .twitchPurple11 }
    var backgroundOverlayErrorColor: UIColor { return .twitchRed11 }
    var backgroundOverlayInfoColor: UIColor { return .twitchBlue12 }
    var backgroundOverlayPlaceholderColor: UIColor { return .twitchOpacW3 }
    var backgroundOverlaySuccessColor: UIColor { return .twitchGreen13 }
    var backgroundOverlayWarnColor: UIColor { return .twitchOrange13 }
    var backgroundPillColor: UIColor { return .twitchHintedGrey7 }
    var backgroundPillNewColor: UIColor { return .twitchMagenta11 }
    var backgroundPillNotificationColor: UIColor { return .twitchRed }
    var backgroundPillSubtleColor: UIColor { return .twitchHintedGrey10 }
    var backgroundPlaceholderColor: UIColor { return .twitchOpacW1 }
    var backgroundPrimeColor: UIColor { return .twitchPrimeBlue }
    var backgroundProgressColor: UIColor { return .twitchOpacW4 }
    var backgroundProgressCountdownStatusColor: UIColor { return .twitchPurple9 }
    var backgroundProgressOverlayMaskColor: UIColor { return .twitchOpacB7 }
    var backgroundProgressOverlayStatusColor: UIColor { return .twitchOpacW12 }
    var backgroundProgressStatusColor: UIColor { return borderBrandColor }
    var backgroundProgressStatusCautionColor: UIColor { return borderWarnColor }
    var backgroundProgressStatusErrorColor: UIColor { return borderErrorColor }
    var backgroundProgressStatusSuccessColor: UIColor { return borderSuccessColor }
    var backgroundRangeColor: UIColor { return .twitchOpacW4 }
    var backgroundRangeFillColor: UIColor { return borderBrandColor }
    var backgroundRangeOverlayColor: UIColor { return .twitchOpacW6 }
    var backgroundRangeOverlayFillColor: UIColor { return .twitchWhite }
    var backgroundScrollbarColor: UIColor { return .twitchHintedGrey3 }
    var backgroundSocialColumnColor: UIColor { return .twitchHintedGrey2 }
    var backgroundSubscriberStreamTagActiveColor: UIColor { return .twitchPurple4 }
    var backgroundSubscriberStreamTagDefaultColor: UIColor { return .twitchPurple4 }
    var backgroundSubscriberStreamTagHoverColor: UIColor { return .twitchPurple3 }
    var backgroundSuccessColor: UIColor { return .twitchGreen13 }
    var backgroundTagActiveColor: UIColor { return backgroundInteractableActiveColor }
    var backgroundTagDefaultColor: UIColor { return .twitchOpacW3 }
    var backgroundTagHoverColor: UIColor { return backgroundInteractableHoverColor }
    var backgroundToggleColor: UIColor { return .twitchTransparent }
    var backgroundToggleCheckedColor: UIColor { return .twitchBlack }
    var backgroundToggleFocusColor: UIColor { return .twitchOpacW5 }
    var backgroundToggleHandleColor: UIColor { return .twitchWhite }
    var backgroundToggleHandleCheckedColor: UIColor { return .twitchPurple10 }
    var backgroundToggleHandleOverlayColor: UIColor { return .twitchWhite }
    var backgroundToggleHoverColor: UIColor { return .twitchOpacW5 }
    var backgroundToggleOverlayColor: UIColor { return .twitchOpacB4 }
    var backgroundToggleOverlayCheckedColor: UIColor { return .twitchBlack }
    var backgroundTooltipColor: UIColor { return .twitchWhite }
    var backgroundTopNavColor: UIColor { return .twitchPurple6 }
    var backgroundWarnColor: UIColor { return .twitchOrange13 }
    var borderAlertColor: UIColor { return .twitchRed }
    var borderBalloonOverlayColor: UIColor { return .twitchOpacW4 }
    var borderBaseColor: UIColor { return .twitchOpacW2 }
    var borderBrandColor: UIColor { return .twitchPurple10 }
    var borderBrandDecorativeColor: UIColor { return .twitchPurple10 }
    var borderButtonColor: UIColor { return .twitchPurple7 }
    var borderButtonActiveColor: UIColor { return .twitchPurple8 }
    var borderButtonAlertColor: UIColor { return .twitchRed }
    var borderButtonAlertActiveColor: UIColor { return .twitchRed }
    var borderButtonAlertFocusColor: UIColor { return .twitchRedDarker }
    var borderButtonAlertHoverColor: UIColor { return .twitchRedDarker }
    var borderButtonDisabledColor: UIColor { return .twitchOpacW1 }
    var borderButtonFocusColor: UIColor { return .twitchPurple9 }
    var borderButtonHoverColor: UIColor { return .twitchPurple8 }
    var borderButtonOverlayColor: UIColor { return .twitchTransparent }
    var borderButtonOverlayActiveColor: UIColor { return .twitchOpacW9 }
    var borderButtonOverlayBorderedColor: UIColor { return .twitchWhite }
    var borderButtonOverlayFocusColor: UIColor { return .twitchOpacW6 }
    var borderButtonOverlayHoverColor: UIColor { return .twitchTransparent }
    var borderButtonStatusColor: UIColor { return .twitchGreen }
    var borderButtonStatusActiveColor: UIColor { return .twitchRed }
    var borderButtonStatusFocusColor: UIColor { return .twitchRedDarker }
    var borderButtonStatusHoverColor: UIColor { return .twitchRedDarker }
    var borderButtonSuccessColor: UIColor { return .twitchGreen }
    var borderButtonSuccessActiveColor: UIColor { return .twitchGreen }
    var borderButtonSuccessFocusColor: UIColor { return .twitchGreen }
    var borderButtonSuccessHoverColor: UIColor { return .twitchGreen }
    var borderErrorColor: UIColor { return .twitchRed10 }
    var borderErrorDecorativeColor: UIColor { return .twitchRed10 }
    var borderImageSelectorColor: UIColor { return .twitchOpacB6 }
    var borderImageSelectorOverlayColor: UIColor { return .twitchOpacW6 }
    var borderImageSelectorOverlaySelectedColor: UIColor { return .twitchWhite }
    var borderInfoColor: UIColor { return .twitchBlue10 }
    var borderInfoDecorativeColor: UIColor { return .twitchBlue10 }
    var borderInputColor: UIColor { return .twitchOpacW4 }
    var borderInputCheckboxColor: UIColor { return .twitchOpacW10 }
    var borderInputCheckboxCheckedColor: UIColor { return borderBrandColor }
    var borderInputCheckboxCheckedOverlayColor: UIColor { return .twitchWhite }
    var borderInputCheckboxErrorColor: UIColor { return borderErrorColor }
    var borderInputCheckboxFocusColor: UIColor { return borderBrandColor }
    var borderInputCheckboxHoverColor: UIColor { return .twitchWhite }
    var borderInputCheckboxHoverOverlayColor: UIColor { return .twitchWhite }
    var borderInputCheckboxOverlayColor: UIColor { return .twitchOpacW10 }
    var borderInputCheckboxOverlayFocusColor: UIColor { return .twitchWhite }
    var borderInputErrorColor: UIColor { return borderErrorColor }
    var borderInputFocusColor: UIColor { return borderBrandColor }
    var borderInputHoverColor: UIColor { return .twitchOpacW6 }
    var borderInputOverlayColor: UIColor { return .twitchOpacW6 }
    var borderInputOverlayFocusColor: UIColor { return .twitchWhite }
    var borderInputOverlayHoverColor: UIColor { return .twitchOpacW8 }
    var borderInteractableSelectedColor: UIColor { return .twitchPurple10 }
    var borderOverlayColor: UIColor { return .twitchOpacW5 }
    var borderOverlayBrandColor: UIColor { return .twitchWhite }
    var borderOverlayBrandDecorativeColor: UIColor { return .twitchPurple10 }
    var borderOverlayErrorColor: UIColor { return .twitchRed10 }
    var borderOverlayErrorDecorativeColor: UIColor { return .twitchRed10 }
    var borderOverlayInfoColor: UIColor { return .twitchBlue10 }
    var borderOverlayInfoDecorativeColor: UIColor { return .twitchBlue10 }
    var borderOverlaySuccessColor: UIColor { return .twitchGreen12 }
    var borderOverlaySuccessDecorativeColor: UIColor { return .twitchGreen12 }
    var borderOverlayWarnColor: UIColor { return .twitchOrange12 }
    var borderOverlayWarnDecorativeColor: UIColor { return .twitchOrange12 }
    var borderQuoteColor: UIColor { return .twitchHintedGrey6 }
    var borderRangeHandleColor: UIColor { return borderBrandColor }
    var borderRangeHandleFocusColor: UIColor { return .twitchWhite }
    var borderRegionColor: UIColor { return .twitchBlack }
    var borderSelectableColor: UIColor { return .twitchOpacW3 }
    var borderSelectableHoverColor: UIColor { return .twitchOpacW4 }
    var borderSelectableHoverSelectedColor: UIColor { return .twitchOpacB3 }
    var borderSelectableOverlayColor: UIColor { return .twitchOpacW3 }
    var borderSelectableOverlayHoverColor: UIColor { return .twitchOpacW4 }
    var borderSelectableOverlaySelectedColor: UIColor { return .twitchWhite }
    var borderSelectableSelectedInnerColor: UIColor { return .twitchBlack }
    var borderSelectableSelectedOuterColor: UIColor { return .twitchWhite }
    var borderSpinnerColor: UIColor { return .twitchOpacW3 }
    var borderSpinnerFillColor: UIColor { return .twitchHintedGrey12 }
    var borderSubscriberStreamTagColor: UIColor { return .twitchPurple5 }
    var borderSuccessColor: UIColor { return .twitchGreen12 }
    var borderSuccessDecorativeColor: UIColor { return .twitchGreen12 }
    var borderTabColor: UIColor { return borderBaseColor }
    var borderTabActiveColor: UIColor { return borderBrandColor }
    var borderTabFocusColor: UIColor { return .twitchPurple11 }
    var borderTabHoverColor: UIColor { return .twitchPurple11 }
    var borderTagColor: UIColor { return .twitchOpacW3 }
    var borderToggleColor: UIColor { return .twitchOpacW10 }
    var borderToggleCheckedColor: UIColor { return borderBrandColor }
    var borderToggleFocusColor: UIColor { return borderBrandColor }
    var borderToggleHoverColor: UIColor { return .twitchWhite }
    var borderToggleOverlayColor: UIColor { return .twitchOpacW10 }
    var borderToggleOverlayCheckedColor: UIColor { return .twitchWhite }
    var borderToggleOverlayFocusColor: UIColor { return .twitchWhite }
    var borderToggleOverlayHoverColor: UIColor { return .twitchWhite }
    var borderWarnColor: UIColor { return .twitchOrange12 }
    var borderWarnDecorativeColor: UIColor { return .twitchOrange12 }
    var borderWhisperIncomingColor: UIColor { return .twitchPurple10 }
    var borderWhisperOutgoingColor: UIColor { return .twitchHintedGrey9 }
    var fillAlertColor: UIColor { return .twitchError }
    var fillAltColor: UIColor { return textAltColor }
    var fillAlt2Color: UIColor { return textAlt2Color }
    var fillBaseColor: UIColor { return textBaseColor }
    var fillBrandColor: UIColor { return .twitchPurple10 }
    var fillBrandOverlayColor: UIColor { return .twitchPurple10 }
    var fillButtonIconColor: UIColor { return textBaseColor }
    var fillButtonIconActiveColor: UIColor { return textBaseColor }
    var fillButtonIconFocusColor: UIColor { return textBaseColor }
    var fillButtonIconHoverColor: UIColor { return textBaseColor }
    var fillChannelStatusTextIndicatorHostingColor: UIColor { return .twitchOpacW10 }
    var fillChannelStatusTextIndicatorHostingOverlayColor: UIColor { return .twitchOpacW10 }
    var fillChannelStatusTextIndicatorOfflineColor: UIColor { return .twitchWhite }
    var fillChannelStatusTextIndicatorOfflineOverlayColor: UIColor { return .twitchWhite }
    var fillChannelStatusTextIndicatorRerunColor: UIColor { return .twitchOpacW10 }
    var fillChannelStatusTextIndicatorRerunOverlayColor: UIColor { return .twitchOpacW10 }
    var fillCrateColor: UIColor { return .twitchGreen }
    var fillDropsColor: UIColor { return .twitchGreen }
    var fillErrorColor: UIColor { return .twitchRed10 }
    var fillErrorOverlayColor: UIColor { return .twitchRed10 }
    var fillHostingColor: UIColor { return .twitchYellow }
    var fillInfoColor: UIColor { return .twitchBlue10 }
    var fillInfoOverlayColor: UIColor { return .twitchBlue10 }
    var fillLiveColor: UIColor { return .twitchRed }
    var fillOfflineColor: UIColor { return .twitchHintedGrey7 }
    var fillPresenceAwayColor: UIColor { return .twitchWarn }
    var fillPresenceBusyColor: UIColor { return .twitchRed11 }
    var fillPresenceIdleColor: UIColor { return .twitchWarn }
    var fillPresenceInvisibleColor: UIColor { return .twitchHintedGrey9 }
    var fillPresenceOfflineColor: UIColor { return .twitchHintedGrey9 }
    var fillPresenceOnlineColor: UIColor { return .twitchSuccess }
    var fillPrimeColor: UIColor { return .twitchPrimeBlue }
    var fillRangeNotchColor: UIColor { return .twitchHintedGrey7 }
    var fillSuccessColor: UIColor { return .twitchGreen13 }
    var fillSuccessOverlayColor: UIColor { return .twitchGreen13 }
    var fillWarnColor: UIColor { return .twitchOrange12 }
    var fillWarnOverlayColor: UIColor { return .twitchOrange12 }
    var iconInputCheckedColor: UIColor { return .twitchWhite }
    var iconInputRadioCheckedColor: UIColor { return .twitchWhite }
    var socialFacebookColor: UIColor { return .twitchFacebook }
    var socialInstagramColor: UIColor { return .twitchInstagram }
    var socialPaypalColor: UIColor { return .twitchPaypal }
    var socialRedditColor: UIColor { return .twitchReddit }
    var socialSnapchatColor: UIColor { return .twitchSnapchat }
    var socialTwitterColor: UIColor { return .twitchTwitter }
    var socialVkColor: UIColor { return .twitchVk }
    var socialYoutubeColor: UIColor { return .twitchYoutube }
    var textAccessibleBlueColor: UIColor { return .twitchBlue11 }
    var textAccessibleGreenColor: UIColor { return .twitchGreen11 }
    var textAccessibleRedColor: UIColor { return .twitchRed11 }
    var textAlertColor: UIColor { return textAccessibleRedColor }
    var textAltColor: UIColor { return .twitchHintedGrey12 }
    var textAlt2Color: UIColor { return .twitchHintedGrey9 }
    var textBadgeAltColor: UIColor { return .twitchBlack }
    var textBadgeAlt2Color: UIColor { return .twitchBlack }
    var textBaseColor: UIColor { return .twitchHintedGrey14 }
    var textBrandColor: UIColor { return .twitchPurple11 }
    var textButtonColor: UIColor { return .twitchWhite }
    var textButtonActiveColor: UIColor { return .twitchWhite }
    var textButtonAlertColor: UIColor { return .twitchBlack }
    var textButtonAlertActiveColor: UIColor { return .twitchBlack }
    var textButtonAlertFocusColor: UIColor { return .twitchBlack }
    var textButtonAlertHoverColor: UIColor { return .twitchBlack }
    var textButtonBrandColor: UIColor { return .twitchWhite }
    var textButtonDestructiveColor: UIColor { return textButtonErrorColor }
    var textButtonDisabledColor: UIColor { return .twitchOpacW8 }
    var textButtonErrorColor: UIColor { return .twitchBlack }
    var textButtonFocusColor: UIColor { return .twitchWhite }
    var textButtonHoverColor: UIColor { return .twitchWhite }
    var textButtonInfoColor: UIColor { return .twitchBlack }
    var textButtonOverlayColor: UIColor { return .twitchWhite }
    var textButtonOverlayActiveColor: UIColor { return .twitchWhite }
    var textButtonOverlayBrandColor: UIColor { return .twitchBlack }
    var textButtonOverlayErrorColor: UIColor { return .twitchBlack }
    var textButtonOverlayFocusColor: UIColor { return .twitchWhite }
    var textButtonOverlayHoverColor: UIColor { return .twitchWhite }
    var textButtonOverlayInfoColor: UIColor { return .twitchBlack }
    var textButtonOverlayPrimaryColor: UIColor { return .twitchBlack }
    var textButtonOverlaySecondaryColor: UIColor { return .twitchWhite }
    var textButtonOverlaySuccessColor: UIColor { return .twitchBlack }
    var textButtonOverlayTextColor: UIColor { return .twitchWhite }
    var textButtonOverlayWarnColor: UIColor { return .twitchBlack }
    var textButtonPrimaryColor: UIColor { return .twitchWhite }
    var textButtonSecondaryColor: UIColor { return textBaseColor }
    var textButtonSecondaryActiveColor: UIColor { return .twitchHintedGrey6 }
    var textButtonSecondaryFocusColor: UIColor { return .twitchHintedGrey6 }
    var textButtonSecondaryHoverColor: UIColor { return .twitchHintedGrey6 }
    var textButtonStatusColor: UIColor { return .twitchWhite }
    var textButtonStatusActiveColor: UIColor { return .twitchWhite }
    var textButtonStatusFocusColor: UIColor { return .twitchWhite }
    var textButtonStatusHoverColor: UIColor { return .twitchWhite }
    var textButtonSuccessColor: UIColor { return .twitchBlack }
    var textButtonSuccessActiveColor: UIColor { return .twitchBlack }
    var textButtonSuccessFocusColor: UIColor { return .twitchBlack }
    var textButtonSuccessHoverColor: UIColor { return .twitchBlack }
    var textButtonTextColor: UIColor { return textBrandColor }
    var textButtonTextActiveColor: UIColor { return .twitchOpacP2 }
    var textButtonTextFocusColor: UIColor { return .twitchOpacW1 }
    var textButtonTextHoverColor: UIColor { return .twitchOpacW1 }
    var textButtonWarnColor: UIColor { return .twitchBlack }
    var textChannelStatusTextIndicatorHostingColor: UIColor { return .twitchBlack }
    var textChannelStatusTextIndicatorHostingOverlayColor: UIColor { return .twitchBlack }
    var textChannelStatusTextIndicatorOfflineColor: UIColor { return .twitchBlack }
    var textChannelStatusTextIndicatorOfflineOverlayColor: UIColor { return .twitchBlack }
    var textChannelStatusTextIndicatorRerunColor: UIColor { return .twitchBlack }
    var textChannelStatusTextIndicatorRerunOverlayColor: UIColor { return .twitchBlack }
    var textChatLineMentionedColor: UIColor { return .twitchHintedGrey2 }
    var textChatLineMentioningColor: UIColor { return .twitchWhite }
    var textErrorColor: UIColor { return .twitchRed11 }
    var textHintColor: UIColor { return .twitchHintedGrey8 }
    var textInfoColor: UIColor { return .twitchBlue11 }
    var textInputColor: UIColor { return textBaseColor }
    var textInputCheckedIconColor: UIColor { return .twitchWhite }
    var textInputPlaceholderColor: UIColor { return .twitchOpacW10 }
    var textInputPlaceholderOverlayColor: UIColor { return .twitchOpacW10 }
    var textInteractableActiveColor: UIColor { return .twitchWhite }
    var textInteractableHoverColor: UIColor { return .twitchWhite }
    var textInteractableInvertedColor: UIColor { return .twitchWhite }
    var textInteractableOverlaySelectedColor: UIColor { return .twitchBlack }
    var textInteractableSelectedColor: UIColor { return textOverlayColor }
    var textLabelColor: UIColor { return .twitchHintedGrey15 }
    var textLabelOptionalColor: UIColor { return .twitchHintedGrey8 }
    var textLinkColor: UIColor { return .twitchPurple10 }
    var textLinkActiveColor: UIColor { return .twitchPurple10 }
    var textLinkFocusColor: UIColor { return .twitchPurple10 }
    var textLinkHoverColor: UIColor { return .twitchPurple10 }
    var textLinkVisitedColor: UIColor { return .twitchPurple10 }
    var textLiveColor: UIColor { return textAccessibleRedColor }
    var textOverlayColor: UIColor { return .twitchWhite }
    var textOverlayAltColor: UIColor { return .twitchOpacW13 }
    var textOverlayBrandColor: UIColor { return .twitchWhite }
    var textOverlayErrorColor: UIColor { return .twitchRed11 }
    var textOverlayInfoColor: UIColor { return .twitchBlue11 }
    var textOverlayLinkColor: UIColor { return .twitchWhite }
    var textOverlayLinkActiveColor: UIColor { return .twitchPurple13 }
    var textOverlayLinkFocusColor: UIColor { return .twitchPurple13 }
    var textOverlayLinkHoverColor: UIColor { return .twitchPurple13 }
    var textOverlayLinkVisitedColor: UIColor { return .twitchWhite }
    var textOverlaySuccessColor: UIColor { return .twitchGreen11 }
    var textOverlayWarnColor: UIColor { return .twitchOrange11 }
    var textPillColor: UIColor { return .twitchBlack }
    var textPrimeColor: UIColor { return .twitchPrimeBlue }
    var textSuccessColor: UIColor { return .twitchGreen11 }
    var textTabColor: UIColor { return textBaseColor }
    var textTabActiveColor: UIColor { return .twitchPurple11 }
    var textTagColor: UIColor { return .twitchOpacW10 }
    var textToggleCheckedIconColor: UIColor { return borderBrandColor }
    var textToggleCheckedIconOverlayColor: UIColor { return .twitchWhite }
    var textTooltipColor: UIColor { return .twitchPurple1 }
    var textWarnColor: UIColor { return .twitchOrange11 }
}
final class CoreUILightTheme: TWLightAppTheme, TWCoreUITheme, TWThemeProtocol {
    var backgroundAccentColor: UIColor { return .twitchPurple8 }
    var backgroundAccentAltColor: UIColor { return .twitchPurple7 }
    var backgroundAccentAlt2Color: UIColor { return .twitchPurple6 }
    var backgroundAltColor: UIColor { return .twitchHintedGrey14 }
    var backgroundAlt2Color: UIColor { return .twitchHintedGrey13 }
    var backgroundBaseColor: UIColor { return .twitchWhite }
    var backgroundBodyColor: UIColor { return .twitchHintedGrey15 }
    var backgroundBrandColor: UIColor { return .twitchPurple11 }
    var backgroundButtonColor: UIColor { return .twitchPurple7 }
    var backgroundButtonActiveColor: UIColor { return .twitchPurple7 }
    var backgroundButtonAlertColor: UIColor { return .twitchRed }
    var backgroundButtonAlertActiveColor: UIColor { return .twitchRed }
    var backgroundButtonAlertFocusColor: UIColor { return .twitchRedDarker }
    var backgroundButtonAlertHoverColor: UIColor { return .twitchRedDarker }
    var backgroundButtonBrandColor: UIColor { return .twitchPurple9 }
    var backgroundButtonBrandActiveColor: UIColor { return backgroundButtonBrandColor }
    var backgroundButtonBrandHoverColor: UIColor { return .twitchPurple8 }
    var backgroundButtonDestructiveActiveColor: UIColor { return backgroundButtonErrorActiveColor }
    var backgroundButtonDestructiveDefaultColor: UIColor { return backgroundButtonErrorColor }
    var backgroundButtonDestructiveHoverColor: UIColor { return backgroundButtonErrorHoverColor }
    var backgroundButtonDisabledColor: UIColor { return .twitchOpacB1 }
    var backgroundButtonErrorColor: UIColor { return .twitchRed10 }
    var backgroundButtonErrorActiveColor: UIColor { return backgroundButtonErrorColor }
    var backgroundButtonErrorHoverColor: UIColor { return .twitchRed12 }
    var backgroundButtonFocusColor: UIColor { return .twitchPurple8 }
    var backgroundButtonHoverColor: UIColor { return .twitchPurple8 }
    var backgroundButtonIconOverlayActiveColor: UIColor { return backgroundInteractableOverlayActiveColor }
    var backgroundButtonIconOverlayDefaultColor: UIColor { return .twitchTransparent }
    var backgroundButtonIconOverlayHoverColor: UIColor { return backgroundInteractableOverlayHoverColor }
    var backgroundButtonInfoColor: UIColor { return .twitchBlue11 }
    var backgroundButtonInfoActiveColor: UIColor { return backgroundButtonInfoColor }
    var backgroundButtonInfoHoverColor: UIColor { return .twitchBlue13 }
    var backgroundButtonOverlayColor: UIColor { return .twitchTransparent }
    var backgroundButtonOverlayActiveColor: UIColor { return .twitchOpacW2 }
    var backgroundButtonOverlayBrandColor: UIColor { return .twitchWhite }
    var backgroundButtonOverlayBrandActiveColor: UIColor { return backgroundButtonOverlayBrandColor }
    var backgroundButtonOverlayBrandHoverColor: UIColor { return .twitchOpacW14 }
    var backgroundButtonOverlayDisabledColor: UIColor { return .twitchOpacW2 }
    var backgroundButtonOverlayErrorColor: UIColor { return backgroundButtonErrorColor }
    var backgroundButtonOverlayErrorActiveColor: UIColor { return backgroundButtonOverlayErrorColor }
    var backgroundButtonOverlayErrorHoverColor: UIColor { return backgroundButtonErrorHoverColor }
    var backgroundButtonOverlayFocusColor: UIColor { return .twitchOpacW1 }
    var backgroundButtonOverlayHoverColor: UIColor { return .twitchOpacW1 }
    var backgroundButtonOverlayInfoColor: UIColor { return .twitchBlue11 }
    var backgroundButtonOverlayInfoActiveColor: UIColor { return backgroundButtonOverlayInfoColor }
    var backgroundButtonOverlayInfoHoverColor: UIColor { return .twitchBlue13 }
    var backgroundButtonOverlayPrimaryActiveColor: UIColor { return .twitchOpacW13 }
    var backgroundButtonOverlayPrimaryDefaultColor: UIColor { return .twitchWhite }
    var backgroundButtonOverlayPrimaryHoverColor: UIColor { return .twitchOpacW14 }
    var backgroundButtonOverlaySecondaryActiveColor: UIColor { return backgroundInteractableOverlayActiveColor }
    var backgroundButtonOverlaySecondaryDefaultColor: UIColor { return .twitchOpacW3 }
    var backgroundButtonOverlaySecondaryHoverColor: UIColor { return backgroundInteractableOverlayHoverColor }
    var backgroundButtonOverlaySuccessColor: UIColor { return backgroundButtonSuccessColor }
    var backgroundButtonOverlaySuccessActiveColor: UIColor { return backgroundButtonOverlaySuccessColor }
    var backgroundButtonOverlaySuccessHoverColor: UIColor { return backgroundButtonSuccessHoverColor }
    var backgroundButtonOverlayTextActiveColor: UIColor { return backgroundInteractableOverlayActiveColor }
    var backgroundButtonOverlayTextDefaultColor: UIColor { return .twitchTransparent }
    var backgroundButtonOverlayTextHoverColor: UIColor { return backgroundInteractableOverlayHoverColor }
    var backgroundButtonOverlayWarnColor: UIColor { return .twitchOrange12 }
    var backgroundButtonOverlayWarnActiveColor: UIColor { return backgroundButtonOverlayWarnColor }
    var backgroundButtonOverlayWarnHoverColor: UIColor { return .twitchOrange14 }
    var backgroundButtonPrimaryActiveColor: UIColor { return backgroundButtonBrandActiveColor }
    var backgroundButtonPrimaryDefaultColor: UIColor { return backgroundButtonBrandColor }
    var backgroundButtonPrimaryHoverColor: UIColor { return backgroundButtonBrandHoverColor }
    var backgroundButtonPurchaseColor: UIColor { return .twitchOpacB5 }
    var backgroundButtonSecondaryActiveColor: UIColor { return backgroundInteractableActiveColor }
    var backgroundButtonSecondaryDefaultColor: UIColor { return .twitchOpacB1 }
    var backgroundButtonSecondaryHoverColor: UIColor { return backgroundInteractableHoverColor }
    var backgroundButtonStatusColor: UIColor { return backgroundButtonSuccessColor }
    var backgroundButtonStatusActiveColor: UIColor { return backgroundButtonErrorActiveColor }
    var backgroundButtonStatusFocusColor: UIColor { return backgroundButtonErrorHoverColor }
    var backgroundButtonStatusHoverColor: UIColor { return backgroundButtonErrorHoverColor }
    var backgroundButtonSuccessColor: UIColor { return .twitchGreen12 }
    var backgroundButtonSuccessActiveColor: UIColor { return backgroundButtonSuccessColor }
    var backgroundButtonSuccessFocusColor: UIColor { return .twitchGreenDarker }
    var backgroundButtonSuccessHoverColor: UIColor { return .twitchGreen14 }
    var backgroundButtonTextActiveColor: UIColor { return backgroundInteractableActiveColor }
    var backgroundButtonTextDefaultColor: UIColor { return .twitchTransparent }
    var backgroundButtonTextHoverColor: UIColor { return backgroundInteractableHoverColor }
    var backgroundButtonWarnColor: UIColor { return .twitchOrange12 }
    var backgroundButtonWarnActiveColor: UIColor { return backgroundButtonWarnColor }
    var backgroundButtonWarnHoverColor: UIColor { return .twitchOrange14 }
    var backgroundChatColor: UIColor { return .twitchHintedGrey15 }
    var backgroundChatAltColor: UIColor { return .twitchHintedGrey14 }
    var backgroundChatHeaderColor: UIColor { return .twitchHintedGrey15 }
    var backgroundChatLineMentionedColor: UIColor { return .twitchHintedGrey1 }
    var backgroundChatLineMentioningColor: UIColor { return .twitchHintedGrey12 }
    var backgroundErrorColor: UIColor { return .twitchRed11 }
    var backgroundFloatColor: UIColor { return .twitchWhite }
    var backgroundGraphColor: UIColor { return .twitchPurple15 }
    var backgroundGraphFillColor: UIColor { return .twitchPurple9 }
    var backgroundImageSelectorOverlayColor: UIColor { return .twitchTransparent }
    var backgroundInfoColor: UIColor { return .twitchBlue12 }
    var backgroundInputColor: UIColor { return .twitchOpacB2 }
    var backgroundInputCheckboxCheckedColor: UIColor { return borderBrandColor }
    var backgroundInputCheckboxCheckedBackgroundColor: UIColor { return .twitchWhite }
    var backgroundInputCheckboxCheckedBackgroundOverlayColor: UIColor { return .twitchBlack }
    var backgroundInputCheckboxCheckedOverlayColor: UIColor { return .twitchWhite }
    var backgroundInputCheckedColor: UIColor { return .twitchPurple8 }
    var backgroundInputFocusColor: UIColor { return .twitchWhite }
    var backgroundInputOverlayColor: UIColor { return .twitchOpacB4 }
    var backgroundInputOverlayFocusColor: UIColor { return .twitchBlack }
    var backgroundInteractableActiveColor: UIColor { return .twitchOpacB1 }
    var backgroundInteractableAlphaActiveColor: UIColor { return .twitchOpacB2 }
    var backgroundInteractableAlphaHoverColor: UIColor { return .twitchOpacB1 }
    var backgroundInteractableAlphaSelectedColor: UIColor { return .twitchOpacB1 }
    var backgroundInteractableDestructiveActiveColor: UIColor { return .twitchRed }
    var backgroundInteractableDestructiveHoverColor: UIColor { return .twitchRedDarker }
    var backgroundInteractableHoverColor: UIColor { return .twitchOpacB2 }
    var backgroundInteractableOverlayActiveColor: UIColor { return .twitchOpacW3 }
    var backgroundInteractableOverlayHoverColor: UIColor { return .twitchOpacW4 }
    var backgroundInteractableOverlaySelectedColor: UIColor { return .twitchWhite }
    var backgroundInteractableSelectedColor: UIColor { return backgroundButtonBrandColor }
    var backgroundLiveColor: UIColor { return .twitchRed }
    var backgroundModalColor: UIColor { return .twitchWhite }
    var backgroundModalOverlayColor: UIColor { return .twitchOpacB13 }
    var backgroundOverlayColor: UIColor { return .twitchOpacB9 }
    var backgroundOverlayBrandColor: UIColor { return .twitchPurple11 }
    var backgroundOverlayErrorColor: UIColor { return .twitchRed11 }
    var backgroundOverlayInfoColor: UIColor { return .twitchBlue12 }
    var backgroundOverlayPlaceholderColor: UIColor { return .twitchOpacW3 }
    var backgroundOverlaySuccessColor: UIColor { return .twitchGreen13 }
    var backgroundOverlayWarnColor: UIColor { return .twitchOrange13 }
    var backgroundPillColor: UIColor { return .twitchHintedGrey7 }
    var backgroundPillNewColor: UIColor { return .twitchMagenta11 }
    var backgroundPillNotificationColor: UIColor { return .twitchRed }
    var backgroundPillSubtleColor: UIColor { return .twitchHintedGrey10 }
    var backgroundPlaceholderColor: UIColor { return .twitchOpacB1 }
    var backgroundPrimeColor: UIColor { return .twitchPrimeBlue }
    var backgroundProgressColor: UIColor { return .twitchHintedGrey12 }
    var backgroundProgressCountdownStatusColor: UIColor { return .twitchPurple8 }
    var backgroundProgressOverlayMaskColor: UIColor { return .twitchOpacB7 }
    var backgroundProgressOverlayStatusColor: UIColor { return .twitchOpacW12 }
    var backgroundProgressStatusColor: UIColor { return borderBrandColor }
    var backgroundProgressStatusCautionColor: UIColor { return borderWarnColor }
    var backgroundProgressStatusErrorColor: UIColor { return borderErrorColor }
    var backgroundProgressStatusSuccessColor: UIColor { return borderSuccessColor }
    var backgroundRangeColor: UIColor { return .twitchOpacB4 }
    var backgroundRangeFillColor: UIColor { return borderBrandColor }
    var backgroundRangeOverlayColor: UIColor { return .twitchOpacW6 }
    var backgroundRangeOverlayFillColor: UIColor { return .twitchWhite }
    var backgroundScrollbarColor: UIColor { return .twitchOpacB3 }
    var backgroundSocialColumnColor: UIColor { return .twitchHintedGrey15 }
    var backgroundSubscriberStreamTagActiveColor: UIColor { return .twitchPurple13 }
    var backgroundSubscriberStreamTagDefaultColor: UIColor { return .twitchPurple13 }
    var backgroundSubscriberStreamTagHoverColor: UIColor { return .twitchPurple14 }
    var backgroundSuccessColor: UIColor { return .twitchGreen13 }
    var backgroundTagActiveColor: UIColor { return backgroundInteractableActiveColor }
    var backgroundTagDefaultColor: UIColor { return .twitchOpacB1 }
    var backgroundTagHoverColor: UIColor { return backgroundInteractableHoverColor }
    var backgroundToggleColor: UIColor { return .twitchTransparent }
    var backgroundToggleCheckedColor: UIColor { return .twitchWhite }
    var backgroundToggleFocusColor: UIColor { return .twitchOpacB7 }
    var backgroundToggleHandleColor: UIColor { return .twitchBlack }
    var backgroundToggleHandleCheckedColor: UIColor { return .twitchPurple8 }
    var backgroundToggleHandleOverlayColor: UIColor { return .twitchWhite }
    var backgroundToggleHoverColor: UIColor { return .twitchOpacB9 }
    var backgroundToggleOverlayColor: UIColor { return .twitchOpacB4 }
    var backgroundToggleOverlayCheckedColor: UIColor { return .twitchBlack }
    var backgroundTooltipColor: UIColor { return .twitchPurple1 }
    var backgroundTopNavColor: UIColor { return .twitchPurple7 }
    var backgroundWarnColor: UIColor { return .twitchOrange13 }
    var borderAlertColor: UIColor { return .twitchRed }
    var borderBalloonOverlayColor: UIColor { return .twitchOpacW4 }
    var borderBaseColor: UIColor { return .twitchOpacB2 }
    var borderBrandColor: UIColor { return .twitchPurple8 }
    var borderBrandDecorativeColor: UIColor { return .twitchPurple9 }
    var borderButtonColor: UIColor { return .twitchPurple7 }
    var borderButtonActiveColor: UIColor { return .twitchPurple8 }
    var borderButtonAlertColor: UIColor { return .twitchRed }
    var borderButtonAlertActiveColor: UIColor { return .twitchRed }
    var borderButtonAlertFocusColor: UIColor { return .twitchRedDarker }
    var borderButtonAlertHoverColor: UIColor { return .twitchRedDarker }
    var borderButtonDisabledColor: UIColor { return .twitchOpacB1 }
    var borderButtonFocusColor: UIColor { return .twitchPurple9 }
    var borderButtonHoverColor: UIColor { return .twitchPurple8 }
    var borderButtonOverlayColor: UIColor { return .twitchTransparent }
    var borderButtonOverlayActiveColor: UIColor { return .twitchOpacW9 }
    var borderButtonOverlayBorderedColor: UIColor { return .twitchWhite }
    var borderButtonOverlayFocusColor: UIColor { return .twitchOpacW6 }
    var borderButtonOverlayHoverColor: UIColor { return .twitchTransparent }
    var borderButtonStatusColor: UIColor { return .twitchGreen }
    var borderButtonStatusActiveColor: UIColor { return .twitchRed }
    var borderButtonStatusFocusColor: UIColor { return .twitchRedDarker }
    var borderButtonStatusHoverColor: UIColor { return .twitchRedDarker }
    var borderButtonSuccessColor: UIColor { return .twitchGreen }
    var borderButtonSuccessActiveColor: UIColor { return .twitchGreen }
    var borderButtonSuccessFocusColor: UIColor { return .twitchGreen }
    var borderButtonSuccessHoverColor: UIColor { return .twitchGreen }
    var borderErrorColor: UIColor { return .twitchRed8 }
    var borderErrorDecorativeColor: UIColor { return .twitchRed10 }
    var borderImageSelectorColor: UIColor { return .twitchOpacB6 }
    var borderImageSelectorOverlayColor: UIColor { return .twitchOpacW6 }
    var borderImageSelectorOverlaySelectedColor: UIColor { return .twitchWhite }
    var borderInfoColor: UIColor { return .twitchBlue8 }
    var borderInfoDecorativeColor: UIColor { return .twitchBlue10 }
    var borderInputColor: UIColor { return .twitchOpacB2 }
    var borderInputCheckboxColor: UIColor { return .twitchOpacB10 }
    var borderInputCheckboxCheckedColor: UIColor { return borderBrandColor }
    var borderInputCheckboxCheckedOverlayColor: UIColor { return .twitchWhite }
    var borderInputCheckboxErrorColor: UIColor { return borderErrorColor }
    var borderInputCheckboxFocusColor: UIColor { return borderBrandColor }
    var borderInputCheckboxHoverColor: UIColor { return .twitchBlack }
    var borderInputCheckboxHoverOverlayColor: UIColor { return .twitchWhite }
    var borderInputCheckboxOverlayColor: UIColor { return .twitchOpacW10 }
    var borderInputCheckboxOverlayFocusColor: UIColor { return .twitchWhite }
    var borderInputErrorColor: UIColor { return borderErrorColor }
    var borderInputFocusColor: UIColor { return borderBrandColor }
    var borderInputHoverColor: UIColor { return .twitchOpacB4 }
    var borderInputOverlayColor: UIColor { return .twitchOpacW6 }
    var borderInputOverlayFocusColor: UIColor { return .twitchWhite }
    var borderInputOverlayHoverColor: UIColor { return .twitchOpacW8 }
    var borderInteractableSelectedColor: UIColor { return .twitchPurple9 }
    var borderOverlayColor: UIColor { return .twitchOpacW5 }
    var borderOverlayBrandColor: UIColor { return .twitchWhite }
    var borderOverlayBrandDecorativeColor: UIColor { return .twitchPurple10 }
    var borderOverlayErrorColor: UIColor { return .twitchRed10 }
    var borderOverlayErrorDecorativeColor: UIColor { return .twitchRed10 }
    var borderOverlayInfoColor: UIColor { return .twitchBlue10 }
    var borderOverlayInfoDecorativeColor: UIColor { return .twitchBlue10 }
    var borderOverlaySuccessColor: UIColor { return .twitchGreen12 }
    var borderOverlaySuccessDecorativeColor: UIColor { return .twitchGreen12 }
    var borderOverlayWarnColor: UIColor { return .twitchOrange12 }
    var borderOverlayWarnDecorativeColor: UIColor { return .twitchOrange12 }
    var borderQuoteColor: UIColor { return .twitchHintedGrey7 }
    var borderRangeHandleColor: UIColor { return borderBrandColor }
    var borderRangeHandleFocusColor: UIColor { return .twitchBlack }
    var borderRegionColor: UIColor { return .twitchHintedGrey13 }
    var borderSelectableColor: UIColor { return .twitchOpacB1 }
    var borderSelectableHoverColor: UIColor { return .twitchOpacB2 }
    var borderSelectableHoverSelectedColor: UIColor { return .twitchOpacB3 }
    var borderSelectableOverlayColor: UIColor { return .twitchOpacW3 }
    var borderSelectableOverlayHoverColor: UIColor { return .twitchOpacW4 }
    var borderSelectableOverlaySelectedColor: UIColor { return .twitchWhite }
    var borderSelectableSelectedInnerColor: UIColor { return .twitchWhite }
    var borderSelectableSelectedOuterColor: UIColor { return .twitchBlack }
    var borderSpinnerColor: UIColor { return .twitchOpacB3 }
    var borderSpinnerFillColor: UIColor { return .twitchHintedGrey2 }
    var borderSubscriberStreamTagColor: UIColor { return .twitchPurple10 }
    var borderSuccessColor: UIColor { return .twitchGreen8 }
    var borderSuccessDecorativeColor: UIColor { return .twitchGreen12 }
    var borderTabColor: UIColor { return borderBaseColor }
    var borderTabActiveColor: UIColor { return borderBrandColor }
    var borderTabFocusColor: UIColor { return .twitchPurple9 }
    var borderTabHoverColor: UIColor { return .twitchPurple9 }
    var borderTagColor: UIColor { return .twitchOpacB1 }
    var borderToggleColor: UIColor { return .twitchOpacB10 }
    var borderToggleCheckedColor: UIColor { return borderBrandColor }
    var borderToggleFocusColor: UIColor { return borderBrandColor }
    var borderToggleHoverColor: UIColor { return .twitchBlack }
    var borderToggleOverlayColor: UIColor { return .twitchOpacW10 }
    var borderToggleOverlayCheckedColor: UIColor { return .twitchWhite }
    var borderToggleOverlayFocusColor: UIColor { return .twitchWhite }
    var borderToggleOverlayHoverColor: UIColor { return .twitchWhite }
    var borderWarnColor: UIColor { return .twitchOrange8 }
    var borderWarnDecorativeColor: UIColor { return .twitchOrange12 }
    var borderWhisperIncomingColor: UIColor { return .twitchPurple10 }
    var borderWhisperOutgoingColor: UIColor { return .twitchHintedGrey9 }
    var fillAlertColor: UIColor { return .twitchError }
    var fillAltColor: UIColor { return textAltColor }
    var fillAlt2Color: UIColor { return textAlt2Color }
    var fillBaseColor: UIColor { return textBaseColor }
    var fillBrandColor: UIColor { return .twitchPurple9 }
    var fillBrandOverlayColor: UIColor { return .twitchPurple10 }
    var fillButtonIconColor: UIColor { return textBaseColor }
    var fillButtonIconActiveColor: UIColor { return textBaseColor }
    var fillButtonIconFocusColor: UIColor { return textBaseColor }
    var fillButtonIconHoverColor: UIColor { return textBaseColor }
    var fillChannelStatusTextIndicatorHostingColor: UIColor { return .twitchOpacB10 }
    var fillChannelStatusTextIndicatorHostingOverlayColor: UIColor { return .twitchOpacW10 }
    var fillChannelStatusTextIndicatorOfflineColor: UIColor { return .twitchBlack }
    var fillChannelStatusTextIndicatorOfflineOverlayColor: UIColor { return .twitchWhite }
    var fillChannelStatusTextIndicatorRerunColor: UIColor { return .twitchOpacB10 }
    var fillChannelStatusTextIndicatorRerunOverlayColor: UIColor { return .twitchOpacW10 }
    var fillCrateColor: UIColor { return .twitchGreen }
    var fillDropsColor: UIColor { return .twitchGreen }
    var fillErrorColor: UIColor { return .twitchRed9 }
    var fillErrorOverlayColor: UIColor { return .twitchRed10 }
    var fillHostingColor: UIColor { return .twitchYellow }
    var fillInfoColor: UIColor { return .twitchBlue9 }
    var fillInfoOverlayColor: UIColor { return .twitchBlue10 }
    var fillLiveColor: UIColor { return .twitchRed }
    var fillOfflineColor: UIColor { return .twitchHintedGrey9 }
    var fillPresenceAwayColor: UIColor { return .twitchWarn }
    var fillPresenceBusyColor: UIColor { return .twitchRed7 }
    var fillPresenceIdleColor: UIColor { return .twitchWarn }
    var fillPresenceInvisibleColor: UIColor { return .twitchHintedGrey8 }
    var fillPresenceOfflineColor: UIColor { return .twitchHintedGrey8 }
    var fillPresenceOnlineColor: UIColor { return .twitchSuccess }
    var fillPrimeColor: UIColor { return .twitchPrimeBlue }
    var fillRangeNotchColor: UIColor { return .twitchHintedGrey9 }
    var fillSuccessColor: UIColor { return .twitchGreen9 }
    var fillSuccessOverlayColor: UIColor { return .twitchGreen13 }
    var fillWarnColor: UIColor { return .twitchOrange9 }
    var fillWarnOverlayColor: UIColor { return .twitchOrange12 }
    var iconInputCheckedColor: UIColor { return .twitchWhite }
    var iconInputRadioCheckedColor: UIColor { return .twitchWhite }
    var socialFacebookColor: UIColor { return .twitchFacebook }
    var socialInstagramColor: UIColor { return .twitchInstagram }
    var socialPaypalColor: UIColor { return .twitchPaypal }
    var socialRedditColor: UIColor { return .twitchReddit }
    var socialSnapchatColor: UIColor { return .twitchSnapchat }
    var socialTwitterColor: UIColor { return .twitchTwitter }
    var socialVkColor: UIColor { return .twitchVk }
    var socialYoutubeColor: UIColor { return .twitchYoutube }
    var textAccessibleBlueColor: UIColor { return .twitchBlue7 }
    var textAccessibleGreenColor: UIColor { return .twitchGreen7 }
    var textAccessibleRedColor: UIColor { return .twitchRed7 }
    var textAlertColor: UIColor { return textAccessibleRedColor }
    var textAltColor: UIColor { return .twitchHintedGrey3 }
    var textAlt2Color: UIColor { return .twitchHintedGrey7 }
    var textBadgeAltColor: UIColor { return .twitchWhite }
    var textBadgeAlt2Color: UIColor { return .twitchWhite }
    var textBaseColor: UIColor { return .twitchHintedGrey1 }
    var textBrandColor: UIColor { return .twitchPurple7 }
    var textButtonColor: UIColor { return .twitchWhite }
    var textButtonActiveColor: UIColor { return .twitchWhite }
    var textButtonAlertColor: UIColor { return .twitchBlack }
    var textButtonAlertActiveColor: UIColor { return .twitchBlack }
    var textButtonAlertFocusColor: UIColor { return .twitchBlack }
    var textButtonAlertHoverColor: UIColor { return .twitchBlack }
    var textButtonBrandColor: UIColor { return .twitchWhite }
    var textButtonDestructiveColor: UIColor { return textButtonErrorColor }
    var textButtonDisabledColor: UIColor { return .twitchOpacB6 }
    var textButtonErrorColor: UIColor { return .twitchBlack }
    var textButtonFocusColor: UIColor { return .twitchWhite }
    var textButtonHoverColor: UIColor { return .twitchWhite }
    var textButtonInfoColor: UIColor { return .twitchBlack }
    var textButtonOverlayColor: UIColor { return .twitchWhite }
    var textButtonOverlayActiveColor: UIColor { return .twitchWhite }
    var textButtonOverlayBrandColor: UIColor { return .twitchBlack }
    var textButtonOverlayErrorColor: UIColor { return .twitchBlack }
    var textButtonOverlayFocusColor: UIColor { return .twitchWhite }
    var textButtonOverlayHoverColor: UIColor { return .twitchWhite }
    var textButtonOverlayInfoColor: UIColor { return .twitchBlack }
    var textButtonOverlayPrimaryColor: UIColor { return .twitchBlack }
    var textButtonOverlaySecondaryColor: UIColor { return textOverlayColor }
    var textButtonOverlaySuccessColor: UIColor { return .twitchBlack }
    var textButtonOverlayTextColor: UIColor { return .twitchWhite }
    var textButtonOverlayWarnColor: UIColor { return .twitchBlack }
    var textButtonPrimaryColor: UIColor { return .twitchWhite }
    var textButtonSecondaryColor: UIColor { return textBaseColor }
    var textButtonSecondaryActiveColor: UIColor { return .twitchHintedGrey9 }
    var textButtonSecondaryFocusColor: UIColor { return .twitchHintedGrey9 }
    var textButtonSecondaryHoverColor: UIColor { return .twitchHintedGrey9 }
    var textButtonStatusColor: UIColor { return .twitchWhite }
    var textButtonStatusActiveColor: UIColor { return .twitchWhite }
    var textButtonStatusFocusColor: UIColor { return .twitchWhite }
    var textButtonStatusHoverColor: UIColor { return .twitchWhite }
    var textButtonSuccessColor: UIColor { return .twitchBlack }
    var textButtonSuccessActiveColor: UIColor { return .twitchBlack }
    var textButtonSuccessFocusColor: UIColor { return .twitchBlack }
    var textButtonSuccessHoverColor: UIColor { return .twitchBlack }
    var textButtonTextColor: UIColor { return textBrandColor }
    var textButtonTextActiveColor: UIColor { return .twitchTransparent }
    var textButtonTextFocusColor: UIColor { return .twitchOpacP1 }
    var textButtonTextHoverColor: UIColor { return .twitchOpacP1 }
    var textButtonWarnColor: UIColor { return .twitchBlack }
    var textChannelStatusTextIndicatorHostingColor: UIColor { return .twitchWhite }
    var textChannelStatusTextIndicatorHostingOverlayColor: UIColor { return .twitchBlack }
    var textChannelStatusTextIndicatorOfflineColor: UIColor { return .twitchWhite }
    var textChannelStatusTextIndicatorOfflineOverlayColor: UIColor { return .twitchBlack }
    var textChannelStatusTextIndicatorRerunColor: UIColor { return .twitchWhite }
    var textChannelStatusTextIndicatorRerunOverlayColor: UIColor { return .twitchBlack }
    var textChatLineMentionedColor: UIColor { return .twitchWhite }
    var textChatLineMentioningColor: UIColor { return .twitchHintedGrey2 }
    var textErrorColor: UIColor { return .twitchRed7 }
    var textHintColor: UIColor { return .twitchHintedGrey7 }
    var textInfoColor: UIColor { return .twitchBlue7 }
    var textInputColor: UIColor { return textBaseColor }
    var textInputCheckedIconColor: UIColor { return .twitchWhite }
    var textInputPlaceholderColor: UIColor { return .twitchOpacB10 }
    var textInputPlaceholderOverlayColor: UIColor { return .twitchOpacW10 }
    var textInteractableActiveColor: UIColor { return .twitchWhite }
    var textInteractableHoverColor: UIColor { return .twitchWhite }
    var textInteractableInvertedColor: UIColor { return .twitchWhite }
    var textInteractableOverlaySelectedColor: UIColor { return textBaseColor }
    var textInteractableSelectedColor: UIColor { return textOverlayColor }
    var textLabelColor: UIColor { return .twitchHintedGrey2 }
    var textLabelOptionalColor: UIColor { return .twitchHintedGrey7 }
    var textLinkColor: UIColor { return .twitchPurple8 }
    var textLinkActiveColor: UIColor { return .twitchPurple9 }
    var textLinkFocusColor: UIColor { return .twitchPurple9 }
    var textLinkHoverColor: UIColor { return .twitchPurple9 }
    var textLinkVisitedColor: UIColor { return .twitchPurple9 }
    var textLiveColor: UIColor { return textAccessibleRedColor }
    var textOverlayColor: UIColor { return .twitchWhite }
    var textOverlayAltColor: UIColor { return .twitchOpacW13 }
    var textOverlayBrandColor: UIColor { return .twitchWhite }
    var textOverlayErrorColor: UIColor { return .twitchRed11 }
    var textOverlayInfoColor: UIColor { return .twitchBlue11 }
    var textOverlayLinkColor: UIColor { return .twitchWhite }
    var textOverlayLinkActiveColor: UIColor { return .twitchPurple13 }
    var textOverlayLinkFocusColor: UIColor { return .twitchPurple13 }
    var textOverlayLinkHoverColor: UIColor { return .twitchPurple13 }
    var textOverlayLinkVisitedColor: UIColor { return .twitchWhite }
    var textOverlaySuccessColor: UIColor { return .twitchGreen11 }
    var textOverlayWarnColor: UIColor { return .twitchOrange11 }
    var textPillColor: UIColor { return .twitchBlack }
    var textPrimeColor: UIColor { return .twitchPrimeBlue }
    var textSuccessColor: UIColor { return .twitchGreen7 }
    var textTabColor: UIColor { return textBaseColor }
    var textTabActiveColor: UIColor { return .twitchPurple8 }
    var textTagColor: UIColor { return .twitchOpacB10 }
    var textToggleCheckedIconColor: UIColor { return borderBrandColor }
    var textToggleCheckedIconOverlayColor: UIColor { return .twitchWhite }
    var textTooltipColor: UIColor { return .twitchWhite }
    var textWarnColor: UIColor { return .twitchOrange7 }
}
